In [104]:
import numpy as np

# c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
# print(c)

# print(c[1, 2])
# print(c[1, :])

# print(c[-2, :])

# print(c[:, -1])

# print(c[1, 1:3])

# c[0, 2] = 20
# print(c)

#==============================

# zero= np.zeros((2,3))

# print(zero)

# one = np.ones((3,3))


# print(one)

# id = np.identity(4)
# print(id)

# full=np.full((2,3),4.)
# print(full)

#==========================

# r = np.random.rand(2,3)

# print(r)


# e=np.random.randint(1,6,size=(1,3))#end is not included
# print(e)

#==============================================================================

# e=np.array([[7, 3 ,9],
#  [7, 7 ,2],
#  [7 ,6 ,6]])
# print(e)


# d = e.copy()

# e[1,1]=20
# print("================")
# print(d)

# print("================")
# print(e)

# print("================")
# print(e**2)

#==============================================================================



# a = np.array([1, 2, 3, 4])

# b = np.array([5,6,7,8])

# d = np.vstack([a,b])

# d=np.concatenate([[a,b]],axis=1)

# print(d)

#==============================================================================


# a=np.arange(1,12,2)
# # print(a)


# d = np.linspace(1,5,4)
# # print(d)


# arr=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# print(arr)

# print(arr.shape)

# s= arr.reshape((7,2))
# print(s)
# print("===================================")
# g = arr.transpose()
# print(g)

# print("===================================")

# f=arr.flat[:]
# print(f)

#==============================================================================


r = np.array([[1,2,3],[4,5,6]])
# print(r)
d = np.append(r,[[7],[8]],axis=1)

print(d)

# u=np.array([[1,2,3,4],[5,6,7,8]])
# print("u","\n",u,"\n")

# u1=np.append(u,[[9,10,11,12]],axis=0) #Underneath 
# print("u1","\n",u1,"\n")

# u2=np.append(u,[[5],[9]],axis=1) #
# print("u2","\n",u2,"\n")


# d =  [[1 2 3 7]
#  [4 5 6 8]]
print("=====================================")
x = np.delete(d,2,axis=1)

# print(x)

print("=====================================")

y = np.insert(x,2,[9,10,11],axis=0)
# print(y)


print("=====================================")

z = np.insert(x,0,[9,10],axis=1)
# print(z)
print("=====================================")

a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(a)

h = a[2:4,0:2]
print(h)


[[1 2 3 7]
 [4 5 6 8]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[11 12]
 [16 17]]
